version: '3.7'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        - NGINX_HOST=${NGINX_SERVER_NAME}
      target: prod
    environment:
      - TZ=Europe/Moscow
    ports:
      - 127.0.0.1:${HOST_HTTP_PORT}:80
    env_file:
      - docker/front/prod.env
    restart: always
